//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusTurbo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarefaStatus
    {
        public int IdStatus { get; set; }
        public string DescricaoStatus { get; set; }
    }
}
