//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusTurbo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        public int IdTarefa { get; set; }
        public string DescricaoTarefa { get; set; }
        public System.DateTime DataTarefa { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    }
}
